# Generated by Django 5.0.3 on 2024-03-31 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.BigIntegerField(unique=True, verbose_name='id транзакции')),
                ('invoice_id', models.CharField(blank=True, null=True, verbose_name='номер операции')),
                ('error_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='код ошибки')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='сообщение об ошибке')),
                ('status', models.CharField(choices=[('AUTHORIZED', 'Ожидает подтверждения'), ('COMPLETED', 'Оплачен'), ('CANCELLED', 'Отменен'), ('DECLINED', 'Отклонен'), ('REFUND', 'Возврат денег')], db_index=True, default='AUTHORIZED', verbose_name='статус')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='сумма')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='детали платежа')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='дата изменения')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
