version: '3.7'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=store
      - POSTGRES_PASSWORD=store
    volumes:
      - db-data:/var/lib/postgresql/data/
  redis:
    image: redis:5
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
  web:
    <<: &web
      build: .
      environment:
        - REDIS_URL=redis://redis
        - CELERY_BROKER_URL=redis://redis
        - DATABASE_URL=postgres://store:store@db/store
      depends_on:
        - db
        - redis
  queue-worker:
    <<: *web
    command: celery -A store worker
  queue-scheduler:
    <<: *web
    command: celery -A store beat
volumes:
  db-data:
  redis-data:
